### ISSUE TITLE
After add files, make all and make test can be compiled successfully, while make runtest  can  not  pass

### ISSUE THREAD

**Issue by xiaoxiaomuyu0** [Coldmooon/Code-for-MPELU#1]
[----------] 12 tests from SGDSolverTest/0, where TypeParam = caffe::CPUDevice<float>
[ RUN      ] SGDSolverTest/0.TestLeastSquaresUpdateLROneHundredth
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.SolverParameter: 1:113: Message type "caffe.SolverParameter" has no field named "layer_wise_reduce".
F0509 09:21:30.853242  5167 test_gradient_based_solver.cpp:56] Check failed: google::protobuf::TextFormat::ParseFromString(proto, &param) 

The latest 'caffe-master' can be  compiled  completely. So the 'caffe-master' files  has no problem.
Is there anyone who meets and solves this problem?

**Comment by cookyecat** [comment]
@xiaoxiaomuyu0 This is because the latest caffe has introduced some new keywords in `caffe.proto`. The changes I made to `caffe.proto` are in `message FillerParameter {}` and `message M2PELUParameter {}` . You can solve your problem by copying them to the latest `caffe.proto`

**Comment by xiaoxiaomuyu0** [comment]
@Coldmooon  Thanks for your answer. I have solved this problem perfectly. Moreover, we should add ' optional M2PELUParameter m2pelu_param = 150; ' in message LayerParameter {}.

**Comment by cookyecat** [comment]
@xiaoxiaomuyu0 You're welcome. Please do not hesitate to ask me if you have any further questions.
