### ISSUE TITLE
I have a question about the code for caffe

### ISSUE THREAD

**Issue by xncaffe** [Coldmooon/Code-for-MPELU#3]
Use your code on caffe can be compiled successfully and successfully trained, but in the right straight visualization: "F0724 12:23:30.799641 24843 layer_factory.hpp:81] Check failed: registry.count(type) == 1 (0 vs. 1) Unknown layer type: M2PELU "

**Comment by cookyecat** [comment]
@xncaffe Sorry for the late reply. I just downloaded the latest caffe, recompiled with MPELU, and trained a LeNet model on mnist with MPELU. But I didn't see that error. Maybe you missed  `m2pelu_layer.hpp`.

The `Caffe` I just used has been uploaded to google driver. 
https://drive.google.com/open?id=0Bxsx0A1s5lTmQ2lyVDFGcHZvQVk

I replaced `ReLU` with `MPELU` in `examples/mnist/lenet_train_test.prototxt`. You can download and test it by running `examples/mnist/train_lenet.sh`.

**Comment by xncaffe** [comment]
Thank you for your reply. I am sure  I have compiled all the scripts you've provided, but there's still the problem above. Due to the inconvenience of browsing Google in China, I would like to ask you to send a file you just uploaded. If you can agreed I would be very grateful. My email address: 563622733@qq.com

**Comment by xncaffe** [comment]
After my experiment found that the test model shows "no such type" because there should be no "test_m2pelu_layer.cpp" file. My c ++ program is poor，so could you try to compile it for my reference?

**Comment by cookyecat** [comment]
@xncaffe Actually, test codes do not work during training and test. They are only used to verify the flow of gradients. Caffe is able to work without compiling test codes. The `zip` pack I emailed you has already included a compiled caffe. But you have to compile it again since the environment on your machine is different.
