### ISSUE TITLE
   type: "taylor"

### ISSUE THREAD

**Issue by 2269866108** [Coldmooon/Code-for-MPELU#4]
Sorry.
Check failed: false Unknown filler name: taylor.
 How can I have  the filter? Can you help me ?

**Comment by cookyecat** [comment]
@2269866108 Many thanks. I didn't realize the bug for so long time. The code of taylor was missed in the `GetFiller` function in `filler.hpp` by mistake. Now it has been updated. Sorry for the inconvenience.
